"""change ngo db

Revision ID: 3e0497f5c914
Revises: 641f8b44f049
Create Date: 2023-07-28 14:38:22.502215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0497f5c914'
down_revision = '641f8b44f049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngotb', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('adminname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngotb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminname', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
