"""initial migration

Revision ID: 641f8b44f049
Revises: 
Create Date: 2023-07-28 09:46:29.367867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641f8b44f049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('successes')
    op.drop_table('volunteers')
    op.drop_table('donations')
    op.drop_table('ngotb')
    op.drop_table('reviews')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fullname'),
    sa.UniqueConstraint('password')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ngotb_Id', sa.INTEGER(), nullable=True),
    sa.Column('review', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ngotb_Id'], ['ngotb.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ngotb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('adminname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), nullable=False),
    sa.Column('image', sa.BLOB(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), nullable=False),
    sa.Column('Location', sa.VARCHAR(length=255), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adminname'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('donations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ngotb_id', sa.INTEGER(), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('donation_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ngotb_id'], ['ngotb.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ngotb_Id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ngotb_Id'], ['ngotb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('successes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ngotb_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['ngotb_id'], ['ngotb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
