"""change ngo db

Revision ID: 7581ade912ba
Revises: 641f8b44f049
Create Date: 2023-07-28 16:15:07.104942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7581ade912ba'
down_revision = '641f8b44f049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngotb', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('adminname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngotb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminname', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
