"""change ngo db

Revision ID: c96b8bffa452
Revises: 3e0497f5c914
Create Date: 2023-07-28 14:58:44.529955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96b8bffa452'
down_revision = '3e0497f5c914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngotb', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngotb', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
